services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: cuerpower
      POSTGRES_PASSWORD: cuerpower
      POSTGRES_DB: cuerpower
    ports:
      - "5433:5432"
    volumes:
      - cuerpower_db_data:/var/lib/postgresql/data

volumes:
  cuerpower_db_data:
